HAI 1.2
I HAS A SINGLETON ITZ NULL

HOW DUZ I GET_SINGLETON
  BOTH OF SINGLETON AN "" R NOT NULL, O RLY?
    YA RLY, FOUND YR SINGLETON
  OIC
  FOUND YR ""
IF U SAY SO

I HAS A MESSAGE

GIMMEH MESSAGE
VISIBLE "Message: " MESSAGE

HOW DUZ I SET_SINGLETON
  SINGLETON R "I CAN HAS SINGLETON"
IF U SAY SO

SET_SINGLETON

VISIBLE "Getting the singleton: " GET_SINGLETON

SET_SINGLETON

VISIBLE "Getting the singleton again: " GET_SINGLETON

KTHXBYE
